package com.moinmankar.outboxsync.Entity;

public enum EventType {
    ORDER_CREATED,
    ORDER_CONFIRMED,
    ORDER_CANCELLED,
    ORDER_COMPLETED,

    //PAYMENT ENUMS
    PAYMENT_INITIATED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,

    //INVENTORY ENUMS
    INVENTORY_RESERVED,
    INVENTORY_RELEASED,
    INVENTORY_OUT_OF_STOCK,

    //NOTIFICATION ENUMS
    NOTIFICATION_SENT,
    NOTIFICATION_FAILED
}
